const actions = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_BOOKING: 'NEW_BOOKING',
  NEW_CONTRACT: 'NEW_CONTRACT',
  UPDATE_CONTRACT: 'UPDATE_CONTRACT',
  SCAN_BOOKING: 'CONFIRM_BOOKING',
  SCAN_CONTRACT: 'CONFIRM_CONTRACT',
  REQUIRED_UPDATE_INFO: 'REQUIRED_UPDATE_INFO',
  RESERVE_FEE_PAID: 'RESERVE_FEE_PAID',
  RESERVE_FEE_RECEIVED: 'RESERVE_FEE_RECEIVED',
  CONTRACT_ACCEPTED: 'CONTRACT_ACCEPTED',
  REST_FEE_PAID: 'REST_FEE_PAID',
  REST_FEE_RECEIVED: 'REST_FEE_RECEIVED',
  ALL_FEE_RECEIVED: 'ALL_FEE_RECEIVED',
  ALL_FEE_PAID: 'ALL_FEE_PAID',
  CANCEL_CONTRACT: 'CANCEL_CONTRACT',
  RESIGN_REQUEST: 'RESIGN_REQUEST',
  REJECT_RESIGN_REQUEST: 'REJECT_RESIGN_REQUEST',
  AGREE_RESIGN_REQUEST: 'AGREE_RESIGN_REQUEST',
};

export default actions;
